package com.sample.pojo;
// Generated 14 Apr, 2015 4:53:12 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name="LOCATIONS"
    ,catalog="TEST"
)
public class Locations  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Locations() {
    }

    public Locations(String name) {
       this.name = name;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="name", nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


